package de.dhbwheidenheim.informatik.springhibernate.oneToManyDemo;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller // This means that this class is a Controller
@RequestMapping(path = "/rsdemo") // This means URL's start with /demo (after Application path)
public class RStestController {
	
	
	@Autowired 
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	// private UserRepository userRepository;
	private RtestRepository rtestRepository;
	
	@Autowired 
	private StestRepository stestRepository;

	//@Autowired
	//RSService service;

	
	@GetMapping(path = "/addAnR") // Map ONLY GET Requests
	public @ResponseBody String addAnR(@RequestParam String rname) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		// So sieht eine klassische Web-Service-Schnittstelle aus...
		// z.B.: http://localhost:8080/rsdemo/addAnR?rname=nummereins
		try {
			Rtest r = new Rtest();
			r.setRname(rname);
			rtestRepository.save(r);
			System.out.println("... R " + rname + " speichern erfolgreich");
			return "OK";
		} catch (Exception e) {
			System.out.println("Speichern nicht erfolgreich");
			return("ERROR " + e);
		}
	}
	
	@GetMapping(path = "/addAnS") // Map ONLY GET Requests
	public @ResponseBody String addAnS(@RequestParam String sname) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		// So sieht eine klassische Web-Service-Schnittstelle aus...
		// z.B.: http://localhost:8080/rsdemo/addAnS?name=nummerzehn
		try {
			Stest s = new Stest();
			s.setSname(sname);
			stestRepository.save(s);
			System.out.println("... S " + sname + " speichern erfolgreich");
			return "OK";
		} catch (Exception e) {
			System.out.println("Speichern nicht erfolgreich");
			return("ERROR " + e);
		}
	}

	@GetMapping(path = "/linkRtoS") // Map ONLY GET Requests
	public @ResponseBody String linkRtoS(@RequestParam int rid, int sid) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		// So sieht eine klassische Web-Service-Schnittstelle aus...
		// z.B.: http://localhost:8080/rsdemo/linkRtoS?rid=2&sid=4
		// z.B.: http://localhost:8080/rsdemo/linkRtoS?rid=2&sid=5
		// z.B.: http://localhost:8080/rsdemo/linkRtoS?rid=2&sid=6
		
		try {
			
			System.out.println("R: " + rid + " soll gelinked werden an S: " + sid);
			
			Optional<Rtest> r = rtestRepository.findById( Integer.valueOf(rid)); // Optionals können Objekte oder auch nix enthalten. 
			Rtest rtest = r.get();
			Optional<Stest> s = stestRepository.findById( Integer.valueOf(sid)); // Optionals können Objekte oder auch nix enthalten. 
			Stest stest = s.get();
			System.out.println("Rtest Instanz: " + rtest );
			System.out.println("Stest Instanz: " + stest );
			stest.setRlink(rtest);
			stestRepository.save(stest);
			/*
			System.out.println("Personenobjekt (from) p1: " + p1);
			Optional<Person> po2 = personRepository.findById( Integer.valueOf(idTo));
			Person p2 = po2.get();
			System.out.println("Personenobjekt (to) p2: " + p2);
			p1.setVerheiratetMit(p2.getId());
			p2.setVerheiratetMit(p1.getId());
			personRepository.save(p1);
			personRepository.save(p2);
			
			Stest s = new Stest();
			s.setSname(sname);
			stestRepository.save(s);
			System.out.println("... S " + sname + " speichern erfolgreich");
			*/
			return "OK";
		} catch (Exception e) {
			System.out.println("Speichern nicht erfolgreich");
			return("ERROR " + e);
		}
	}

	
}
