package de.dhbwheidenheim.informatik.springhibernate.persondemo;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class PersonController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	// private UserRepository userRepository;
	private PersonRepository personRepository;
	
	@Autowired
	private HeiratRepository heiratRepository;

	@Autowired
	PersonService service;

	// @PostMapping(path="/add") // Map ONLY POST Requests
	@GetMapping(path = "/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String vorname, @RequestParam String age) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		// So sieht eine klassische Web-Service-Schnittstelle aus...
		// z.B.: http://localhost:8080/demo/add?name=Rolf&age=58
		try {
			Person p = new Person(name, vorname, Integer.valueOf(age));
			System.out.println("User: " + p + " soll gespeichert werden");
			personRepository.save(p);
			System.out.println("... Speichern erfolgreich");
			return "OK";
		} catch (Exception e) {
			System.out.println("Speichern nicht erfolgreich");
			return("ERROR " + e);
		}
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Person> getAllUsers() {
		// @ResponseBody means the returned String is the response. In diesem Fall JSON
		// z.B.: http://localhost:8080/demo/all
		// This returns a JSON
		// So sieht eine klassische Web-Service-Schnittstelle aus...
		return personRepository.findAll();
	}

	
	@RequestMapping(value = "/list-persons", method = RequestMethod.GET)
	public String showPersons(ModelMap model) {
		// Kein @ResponseBody: Dann benennt der return-String den Namen eines Views.
		// z.B.: http://localhost:8080/demo/list-persons
		// Es wird list-persons.jsp aufgerufen.
		model.put("persons", service.retrievePersons(personRepository));
		model.put("anzahl", service.countPersons(personRepository));
		return "list-persons";
	}

	@RequestMapping(value = "/add-person", method = RequestMethod.GET)
	public String addPersonForm(ModelMap model) {
		// Kein @ResponseBody: Dann benennt der return-String den Namen eines Views.
		// z.B.: http://localhost:8080/demo/add-person
		// Es wird das Eingebeformular add-person.jsp aufgerufen.
		model.put("persons", service.retrievePersons(personRepository));
		return "add-person";
	}

	@RequestMapping(value = "/add-person", method = RequestMethod.POST)
	public String addPerson(ModelMap model, @RequestParam String name, @RequestParam String age) {
		// Kein @ResponseBody: Dann benennt der return-String den Namen eines Views.
		// z.B.: http://localhost:8080/demo/add-person
	    // Das Eingebeformular macht einen POST-Zugriff auf /add-person
		// Die Daten werden gespeichert und anschließend wird list-persons.jsp aufgerufen.
		try {
			service.addPerson(new Person(name, "noVorname", Integer.valueOf(age)), personRepository);
		} catch (Exception e) {
			// Im Fehlerfall wird in list-persons.jsp ein Fehler angezeigt.
			model.put("errorMessage", "Fehlerbeschreibung: " + e);
		}
		model.put("persons", service.retrievePersons(personRepository));
		return "list-persons";
	}
	
	// @PostMapping(path="/makeMariage") // Map ONLY POST Requests
		@GetMapping(path = "/makeMariage") // Map ONLY GET Requests
		public @ResponseBody String makeMariage(@RequestParam int idFrom, @RequestParam int idTo) {
			// @ResponseBody means the returned String is the response, not a view name
			// @RequestParam means it is a parameter from the GET or POST request
			// So sieht eine klassische Web-Service-Schnittstelle aus...
			// z.B.: http://localhost:8080/demo/makeMariage?idFrom=33&idTo=36
			try {
				
				service.makeMariage(idFrom, idTo, personRepository, heiratRepository);
				
				return "OK";
				
			} catch (Exception e) {
				System.out.println("Speichern nicht erfolgreich");
				return("ERROR " + e);
			}
		}
	

	@RequestMapping(value = "/error", method = RequestMethod.POST)
	public String error(ModelMap model, @RequestParam String name, @RequestParam String age) {
		// Tritt ein unbehandelter Fehler auf, dann wird der Error-View in error.jsp gezeigt.
		return "error";
	}

	
}